### ISSUE TITLE
Add localhost / production environmental variables 

### ISSUE THREAD

**Issue by ccrowley96** [ccrowley96/MusiCrowd#6]
We need a way to easily switch between local development and production-ready deployment.

**Comment by chrismaltais** [comment]
It seems like React can just use environment variables as well, and can be called with `process.env.REACT_APP_{WHATEVER}`

I think we also need to load the `dotenv` module for the frontend and require it at the top of all files that use environment variables.

More info:
https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables
